replicaCount: 2

image:
  repository: matanm66/rickandmorty
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5010

ingress:
  enabled: true
  className: nginx
  host: "rickandmorty.local"

resources: {}
