apiVersion: v1
kind: Service
metadata:
  name: {{ include "rickandmorty.fullname" . }}
  namespace: rick-and-morty
  labels:
    app: {{ include "rickandmorty.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rickandmorty.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
