name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Start a minikube cluster
      - name: Setup minikube
        uses: medyagh/setup-minikube@v0.0.18
        with:
          driver: docker

      # Install kubectl and helm, use a fully-qualified kubectl version
      - name: Install kubectl and helm
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            kubectl
            helm
          kubectl: '1.25.0'
          helm: '3.11.1'

      # Verify cluster
      - name: Check cluster pods
        run: kubectl get pods --all-namespaces

      # Deploy the application via Helm
      - name: Helm install
        run: helm install rickandmorty ./helm/rickandmorty --wait

      - name: Get services
        run: kubectl get svc

      # Port-forward to access service locally
      - name: Port forward service
        run: kubectl port-forward svc/rickandmorty-rickandmorty 5010:80 &
      
      - name: Sleep
        run: sleep 10

      # Test endpoints
      - name: Test healthcheck endpoint
        run: curl -f http://localhost:5010/healthcheck

      - name: Test characters endpoint
        run: curl -f http://localhost:5010/characters
