name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 1: Set up a Minikube cluster on the runner
      - name: Setup minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      # Step 2: Install kubectl and helm
      - name: Install kubectl and helm
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            kubectl
            helm
          kubectl: '1.25.0'
          helm: '3.11.1'

      # Step 3: Deploy the Helm chart with ingress disabled
      # Adjust the chart path if needed.
      - name: Helm install application
        run: helm install rickandmorty ./helm/rickandmorty --set ingress.enabled=false --wait --timeout 300s

      # Step 4: List services (for debugging)
      - name: Get services
        run: kubectl get svc --all-namespaces

      # Step 5: Port-forward the service to test locally
      # Assume the service is named 'rickandmorty-rickandmorty' and port 80 maps to 5010 in the pod
      - name: Port forward service
        run: kubectl port-forward svc/rickandmorty-rickandmorty 5010:80 &

      - name: Sleep
        run: sleep 10

      # Step 6: Test the endpoints
      - name: Test healthcheck endpoint
        run: curl -f http://localhost:5010/healthcheck

      - name: Test characters endpoint
        run: curl -f http://localhost:5010/characters
