name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 1: Set up a Minikube cluster on the runner
      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          memory: 4096
          cpus: 2

      # Step 2: Enable Minikube ingress addon
      - name: Enable Minikube Ingress
        run: minikube addons enable ingress

      # Step 3: Install kubectl and helm
      - name: Install kubectl and helm
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            kubectl
            helm
          kubectl: '1.25.0'
          helm: '3.11.1'

      # Step 4: Deploy the Helm chart with ingress enabled
      - name: Helm install application
        run: helm install rickandmorty ./helm/rickandmorty --set ingress.enabled=true --wait --timeout 300s
      
      - name: Debug Pods
        if: failure()
        run: |
            echo "===== PODS ====="
            kubectl get pods -o wide
            for p in $(kubectl get pods -o jsonpath='{.items[*].metadata.name}'); do
              echo "===== DESCRIBE POD: $p ====="
              kubectl describe pod $p
              echo "===== LOGS POD: $p ====="
              kubectl logs $p || true
            done

      # Step 5: List services (for debugging)
      - name: Get services
        run: kubectl get svc --all-namespaces

      # Step 6: Test the endpoints
      - name: Test healthcheck endpoint
        run: curl -f http://localhost/healthcheck

      - name: Test characters endpoint
        run: curl -f http://localhost/characters
